### ISSUE TITLE
This app is illegally attaching my username to an image that has nothing to do with me.

### ISSUE THREAD

**Issue by CheeseKatt** [eightants/reddium#4]
If this is not fixed within 30 days I will be contacting EU authorities per GDPR Law. Even if this is open source (which I love) you have no right to associate my internet submissions with a profile picture I have nothing to do with and  has potential to or is currently harming my brand.  You can reach me here or I will file a lawsuit.

**Comment by eightants** [comment]
Thanks for opening an issue! The approach on Reddium is likely not a GDPR violation. The images are from a fixed size image bank, not of real people, and they are assigned randomly. It is not much different than assigning a number to each user based on the length of their username. I would be interested in the particular article of the GDPR that you feel this approach violates. If not, we can agree that this is not a violation. 

However, I believe that using lifelike avatars assigns a visual race and gender to random users which might cause confusion, so I have switched to an Identicon image bank instead. Hope this answers your question.
